Did some cleanup when it comes to if statements, added more supported filetypes (will look into media type later), did some other improvements to the script as well.

diff --git a/scripts/cprdir b/scripts/cprdir
--- a/scripts/cprdir
+++ b/scripts/cprdir
@@ -1,8 +1,9 @@
 #!/bin/bash
-
+set -eo pipefail
+IFS=$'\n\t'
 
 # Usage
-if [[ "$1" == *"-"*"h"* ]] then
+if [[ "$1" == *"-"*"h"* ]]; then
 	echo "Usage: cprdir [flags] [quality #]"
 	echo "Flags:"
 	echo "	h - Help"
@@ -15,19 +16,25 @@ if [[ "$1" == *"-"*"h"* ]] then
 	echo "	c - Uses more cores to try and compress files more"
 	echo
 	echo "EX: cprdir -yqv 0"
-	exit
+	exit 1
 fi
 
 # Cancellation checks
-# If we skip, skip
-if ! [[ "$1" == *"-"*"y"* ]] && ! [[ "$1" == *"-"*"b"* ]] then
+# Do we have ffmpeg
+if [[ -z "$(command -v ffmpeg)" ]]; then
+	echo "Error: Missing dependency \"ffmpeg\"."
+	exit 1
+fi
+
+# Ask the user if they really want to do this
+if [[ "$1" != *"-"*"y"*  && "$1" != *"-"*"b"* ]]; then
 	echo "This will change images, audio, and maybe videos, found within:"
 	echo "	$(pwd)"
 	read -p "Are you sure you wish to proceed (y/n): " input
 
-	if ! [[ "$input" == "y" ]] then
+	if [[ "$input" != "y" ]]; then
 		echo "You can run this again with flag \"b\" to instead do all operations in a separate directory, thereby maintaining all of the original files."
-		exit
+		exit 0
 	fi
 fi
 
@@ -36,11 +43,14 @@ tempdir="temp-compressing-$RANDOM"
 pwd_val=$(pwd)
 dir_name="${pwd_val##*/}-compressed"
 
-if [[ "$1" == *"-"*"b"* ]] then
+if [[ "$1" == *"-"*"b"* ]]; then
 	# Copy this directory into dir_name, we override already existing compressed dirs
 	cp -r . "../$dir_name"
 	cd "../$dir_name"
 fi
+
+# Cleanup
+trap "rm -rf "$tempdir"" EXIT
 
 
 # Setting up functions
@@ -65,18 +75,25 @@ minTmp() {
 
 # Parameter checks
 qual=25
-if [[ "$1" == *"-"*"q"* ]] && ! [[ -z $2 ]] then
-	qual=$2
+if [[ "$1" == *"-"*"q"* ]]; then
+	if [[ ! -z $2 ]]; then
+		qual=$2
+	else
+		echo "Error: Quality flag set, but quality value not specified."
+		exit 1
+	fi
 fi
 do_vid=false
-if [[ "$1" == *"-"*"v"* ]] then
+if [[ "$1" == *"-"*"v"* ]]; then
 	do_vid=true
 fi
-
+dont_core_max=true
+if [[ "$1" == *"-"*"c"* ]]; then
+	dont_core_max=false
+fi
 do_font=false
-if [[ "$1" == *"-"*"f"* ]] then
-	font_which="$(which fontconv)" # I give up on trying to remove this error output
-	if [[ -z $font_which ]] then
+if [[ "$1" == *"-"*"f"* ]]; then
+	if [[ -z "$(command -v fontconv)" ]]; then
 		echo "Dependency \"fontconv\" not found if you wish to compress fonts please refer to README.md."
 		echo "	Continuing without font compression."
 	else
@@ -89,20 +106,18 @@ fi
 # Starting script
 mkdir "$tempdir"
 
-find . -type f | while read file
+find . -type f | while read f
 do
-	# Fixing file just because easier to do it like this
-	f="$(find | grep "$file")"
-
+	# Tracking variables
 	CMP=0 # Did we compress
 	EXT="" # What file format do we export it as
 
 	# Compressing
 	# Image Case
-	if [[ "$f" == *".png"* ]] || [[ "$f" == *".jpg"* ]] || [[ "$f" == *".jpeg"* ]] || [[ "$f" == *".webp"* ]] then
+	if [[ "$f" == *".png" || "$f" == *".jpg" || "$f" == *".jpeg" || "$f" == *".jfif" || "$f" == *".webp" || "$f" == *".avif" || "$f" == .".jxl" ]]; then
 		# Current Winner: webp, qual 25, comp 2: 21.3 -> 12.5 MB
 		#	0 quality does COMPRESS, but you don't notice 25 quality
-		if ! [[ "$1" == *"-"*"c"* ]] then
+		if $dont_core_max; then
 			ffmpeg -i "$f" -c:v libwebp -compression_level 2 -quality "$qual" "$tempdir/1.webp" -loglevel error -y < /dev/null
 		else
 			ffmpeg -i "$f" -c:v libwebp -compression_level 2 -quality "$qual" "$tempdir/1.webp" -loglevel error -y < /dev/null & PID1=$!
@@ -118,9 +133,9 @@ do
 		EXT=".webp"
 
 	# Audio Case
-	elif [[ "$f" == *".wav"* ]] || [[ "$f" == *".flac"* ]] || [[ "$f" == *".ogg"* ]] || [[ "$f" == *".mp3"* ]] then
+	elif [[ "$f" == *".wav" || "$f" == *".flac" || "$f" == *".ogg" || "$f" == *".mp3" ]]; then
 		# Current winner: ogg, -c:a libvorbis -ab 32k -ar 22050 -b:a 96k: 310.2 -> 93.8 MiB
-		if ! [[ "$1" == *"-"*"c"* ]] then
+		if $dont_core_max; then
 			ffmpeg -i "$f" -c:a libvorbis -ab 32k -ar 22050 -b:a 96k "$tempdir/1.ogg" -loglevel error -y < /dev/null
 		else
 			ffmpeg -i "$f" -c:a libvorbis -ab 32k -ar 22050 -b:a 96k "$tempdir/1.ogg" -loglevel error -y < /dev/null & PID1=$!
@@ -132,14 +147,14 @@ do
 		EXT=".ogg"
 	
 	# Video Case
-	elif $do_vid && ( [[ "$f" == *".webm"* ]] || [[ "$f" == *".mp4"* ]] || [[ "$f" == *".mov"* ]] ) then
+	elif $do_vid && [[ "$f" == *".webm" || "$f" == *".mp4" || "$f" == *".mov" ]]; then
 		echo "Compressing Video: $f"
 		ffmpeg -i "$f" -c:v libvpx -b:v 1M -crf 30 -c:a libopus "$tempdir/1.webm" -loglevel error -y < /dev/null
 		CMP=1
 		EXT=".webm"
 
 	# Font Case
-	elif $do_font && [[ "$f" == *".ttf"* ]] then
+	elif $do_font && [[ "$f" == *".ttf" || "$f" == *".otf" ]]; then
 		fontconv "$f" "$tempdir/1.otf"
 		CMP=1
 		EXT=".otf"
@@ -149,17 +164,10 @@ do
 	if [[ $CMP == 1 ]] then
 		# Get the smallest file
 		smallFile=$(minTmp)
-		if ! [[ "$smallFile" == "$f" ]] then
+		if [[ "$smallFile" != "$f" ]]; then
 			echo "Compressed: $f	$(stat -c%s "$f") -> $(stat -c%s "$smallFile")" # Print the file
 			mv "$smallFile" "$f"
-		fi
-
-		# Cleanup Temp
-		if [[ "$1" == *"-"*"c"* ]] || [[ "$smallFile" == "$f" ]] then
-			rm "$tempdir/"*
 		fi
 	fi
 done
 
-# Cleanup
-rmdir "$tempdir"
