bug fixes and implemented getopts

diff --git a/scripts/cprdir b/scripts/cprdir
--- a/scripts/cprdir
+++ b/scripts/cprdir
@@ -1,9 +1,9 @@
 #!/bin/bash
-set -eo pipefail
+set -euo pipefail
 IFS=$'\n\t'
 
 # Usage
-if [[ "$1" == *"-"*"h"* ]]; then
+usage() {
 	echo "Usage: cprdir [flags] [quality #]"
 	echo "File compression utility which uses FFMPEG to compress lots of files for you."
 	echo
@@ -13,23 +13,62 @@ if [[ "$1" == *"-"*"h"* ]]; then
 	echo "	b - Compress in a different directory (copies the entire directory over)"
 	echo "	v - Include videos (videos take a while)"
 	echo "	f - Include fonts (requires fontconv)"
-	echo "	q - Check for Quality #"
-	echo "		Quality #: Used by ffmpeg for images"
 	echo "	c - Uses more cores to try and compress files more"
+	echo "	q - Check for Quality # (must be last flag)"
+	echo "		Quality #: Used by ffmpeg for images"
 	echo
-	echo "EX: cprdir -yqv 0"
+	echo "EX: cprdir -yvq 0"
 	exit 1
-fi
+}
 
 # Cancellation checks
 # Do we have ffmpeg
 if [[ -z "$(command -v ffmpeg)" ]]; then
 	echo "Error: Missing dependency \"ffmpeg\"."
-	exit 1
+	usage
 fi
 
+# Argument parsing
+yes=false
+backup=false
+do_vid=false
+do_font=false
+dont_core_max=true
+qual=25
+while getopts ":hybvfcq:" opt; do
+	case $opt in
+		h) usage;;
+		y) yes=true;;
+		b) backup=true;;
+		v) do_vid=true;;
+		f)
+			if [[ -z "$(command -v fontconv)" ]]; then
+				echo "Error: Dependency \"fontconv\" not found if you wish to compress fonts please refer to README.md.">&2
+				usage
+			else
+				do_font=true
+			fi
+			;;
+		c) dont_core_max=false;;
+		q)
+			if [[ $OPTARG =~ ^[0-9]+$ ]]; then
+				qual=$OPTARG
+			else
+				echo "Error: Quality value is not a number, \"$OPTARG\".">&2
+				usage
+			fi
+			;;
+		\?) echo "Error: Unknown flag \"$OPTARG\"">&2; usage;;
+		:)
+			echo "Error: Quality flag set, but quality value not specified.">&2
+			usage
+			;;
+	esac
+done
+
+
 # Ask the user if they really want to do this
-if [[ "$1" != "-"*"y"*  && "$1" != "-"*"b"* ]]; then
+if ! $yes && ! $backup; then
 	echo "This will change images, audio, and maybe videos, found within:"
 	echo "	$(pwd)"
 	read -p "Are you sure you wish to proceed (y/n): " input
@@ -44,7 +83,7 @@ fi
 tempdir="temp-compressing-$RANDOM"
 dir_name="${PWD##*/}-compressed"
 
-if [[ "$1" == "-"*"b"* ]]; then
+if $backup; then
 	# Copy this directory into dir_name, we override already existing compressed dirs
 	cp -r . "../$dir_name"
 	cd "../$dir_name"
@@ -73,34 +112,6 @@ min_tmp() {
 	echo "$min_file"
 }
 
-
-# Parameter checks
-qual=25
-if [[ "$1" == "-"*"q"* ]]; then
-	if [[ ! -z $2 ]]; then
-		qual=$2
-	else
-		echo "Error: Quality flag set, but quality value not specified."
-		exit 1
-	fi
-fi
-do_vid=false
-if [[ "$1" == "-"*"v"* ]]; then
-	do_vid=true
-fi
-dont_core_max=true
-if [[ "$1" == "-"*"c"* ]]; then
-	dont_core_max=false
-fi
-do_font=false
-if [[ "$1" == "-"*"f"* ]]; then
-	if [[ -z "$(command -v fontconv)" ]]; then
-		echo "Dependency \"fontconv\" not found if you wish to compress fonts please refer to README.md."
-		echo "	Continuing without font compression."
-	else
-		do_font=true
-	fi
-fi
 
 # Checking if we have an NVIDIA GPU for fast video compression
 nvidia_gpu=false
@@ -169,7 +180,7 @@ do
 	if [[ $cmpr == 1 ]] then
 		# Get the smallest file
 		small_file=$(min_tmp)
-		if [[ "$smallFile" != "$f" ]]; then
+		if [[ "$small_file" != "$f" ]]; then
 			echo "Compressed: $f	$(stat -c%s "$f") -> $(stat -c%s "$small_file")	($(basename "$small_file"))" # Print the file
 			mv "$small_file" "$f"
 		fi
diff --git a/scripts/cprdirdir b/scripts/cprdirdir
--- a/scripts/cprdirdir
+++ b/scripts/cprdirdir
@@ -2,7 +2,7 @@
 set -uo pipefail
 
 # Help command
-if [[ "${1-default}" == *"-h"* ]]; then
+usage() {
 	echo "Usage: cprdirdir [flags] [quality]"
 	echo "Trivial parallelization of cprdir. Opens up cprdir in all subdirectories."
 	echo
@@ -15,11 +15,48 @@ if [[ "${1-default}" == *"-h"* ]]; then
 	echo "	q - Specified quality"
 	echo "	b - Do it in a backup"
 	exit 1
-fi
+}
+
+# Argument parsing
+yes=false
+backup=false
+do_vid=false
+do_font=false
+flags="-y"
+while getopts ":hybvfcq:" opt; do
+	case $opt in
+		h) usage;;
+		y) yes=true;;
+		b) backup=true;;
+		v) flags=$flags" -v";;
+		f)
+			if [[ -z "$(command -v fontconv)" ]]; then
+				echo "Error: Dependency \"fontconv\" not found if you wish to compress fonts please refer to README.md.">&2
+				usage
+			else
+				flags=$flags" -f"
+			fi
+			;;
+		c) flags=$flags" -c";;
+		q)
+			if [[ $OPTARG =~ ^[0-9]+$ ]]; then
+				flags=$flags" -q $OPTARG"
+			else
+				echo "Error: Quality value is not a number, \"$OPTARG\".">&2
+				usage
+			fi
+			;;
+		\?) echo "Error: Unknown flag \"$OPTARG\"">&2; usage;;
+		:)
+			echo "Error: Quality flag set, but quality value not specified.">&2
+			usage
+			;;
+	esac
+done
 
 # MAKING SURE
-if [[ "${1-default}" != *"-"*"y"* && "${1-default}" != *"-"*"b"* ]]; then
-	if [[ "${1-default}" != *"-"*"v"* ]]; then
+if ! $yes && ! $backup; then
+	if ! do_vid; then
 		echo "This will change images, and audio, found within:"
 	else
 		echo "This will change images, audio, and videos, found within:"
@@ -43,25 +80,10 @@ killProcs() {
 
 # Checking for backup
 dir_name="${PWD##*/}-compressed"
-if [[ "$1" == "-"*"b"* ]]; then
+if $backup; then
 	# Copy this directory into dir_name, we override already existing compressed dirs
 	cp -r . "../$dir_name"
 	cd "../$dir_name"
-fi
-
-# Managing flags
-flags="-y"
-if [[ "${1-default}" == *"-"*"v"* ]]; then
-	flags=$flags"v"
-fi
-if [[ "${1-default}" == *"-"*"f"* ]]; then
-	flags=$flags"f"
-fi
-if [[ "${1-default}" == *"-"*"c"* ]]; then
-	flags=$flags"c"
-fi
-if [[ "${1-default}" == *"-"*"q"* ]]; then
-	flags=$flags"q "$2 # If no 2 it should error
 fi
 
 # Starting cprs
